import pygraphviz as pgv

g=pgv.AGraph(directed=True, rankdir='TD', compound=True)

g.add_node("self.z")
g.add_node("self.realData")
g.add_node("self.batchData")

g.add_node("v")
g.add_node("NiceNetworkOperator0,ifMH = False")
g.add_edge("self.z","NiceNetworkOperator0,ifMH = False")
g.add_edge("v","NiceNetworkOperator0,ifMH = False")
g.add_node("self.v_")
g.add_node("self.z_")
g.add_edge("NiceNetworkOperator0,ifMH = False","self.v_")
g.add_edge("NiceNetworkOperator0,ifMH = False","self.z_")

g.add_node("v_")
g.add_node("NiceNetworkOperator1,ifMH = True")
g.add_node("z1")
g.add_node("v1")
g.add_edge("self.z","NiceNetworkOperator1,ifMH = True")
g.add_edge("v_","NiceNetworkOperator1,ifMH = True")
g.add_edge("NiceNetworkOperator1,ifMH = True","z1")
g.add_edge("NiceNetworkOperator1,ifMH = True","v1")

g.add_node("stop_gradient")
g.add_edge("z1","stop_gradient")
g.add_node("z1_")
g.add_edge("stop_gradient","z1_")

g.add_node("v1_")
g.add_node("NiceNetworkOperator2,ifMH = True")
g.add_edge("self.realData","NiceNetworkOperator2,ifMH = True")#,label="abc")
g.add_edge("v1_","NiceNetworkOperator2,ifMH = True")
g.add_edge("NiceNetworkOperator2,ifMH = True","z2")
g.add_edge("NiceNetworkOperator2,ifMH = True","v2")

g.add_node("v2_")
g.add_node("NiceNetworkOperator3,ifMH = True")
g.add_edge("v2_","NiceNetworkOperator3,ifMH = True")
g.add_edge("z1_","NiceNetworkOperator3,ifMH = True")
g.add_edge("NiceNetworkOperator3,ifMH = True","z3")
g.add_edge("NiceNetworkOperator3,ifMH = True","v3")

g.add_node("tf.concat0")
g.add_node("zConcated")
g.add_edge("self.realData","tf.concat")
g.add_edge("z1","tf.concat0")
g.add_edge("z2","tf.concat0")
g.add_edge("z3","tf.concat0")
g.add_edge("tf.concat0","zConcated")

g.add_node("tf.concat1")
g.add_node("vConcated")
g.add_edge("v1","tf.concat1")
g.add_edge("v2","tf.concat1")
g.add_edge("v3","tf.concat1")
g.add_edge("tf.concat1","vConcated")

g.add_node("realData")
g.add_node("batchData")
g.add_node("tf.reshape0")
g.add_node("tf.reshape1")
g.add_edge("self.realData","tf.reshape0")
g.add_edge("tf.reshape0","realData")
g.add_edge("self.batchData","tf.reshape1")
g.add_edge("tf.reshape1","batchData")

g.add_node("GVar")
g.add_edge("GVar","NiceNetworkOperator0,ifMH = False")
g.add_edge("GVar","NiceNetworkOperator1,ifMH = True")
g.add_edge("GVar","NiceNetworkOperator2,ifMH = True")
g.add_edge("GVar","NiceNetworkOperator3,ifMH = True")

g.add_node("rD")
g.add_node("fD")
g.add_node("self.discriminator0")
g.add_node("self.discriminator1")
g.add_node("DVar")
g.add_edge("DVar","self.discriminator0")
g.add_edge("DVar","self.discriminator1")
g.add_edge("realData","self.discriminator0")
g.add_edge("zConcated","self.discriminator1")
g.add_edge("self.discriminator0","rD")
g.add_edge("self.discriminator1","fD")



g.layout('dot')
g.draw('file.png')